--Count
SELECT COUNT(*) FROM SNTD0050 WHERE 0 = 0 ORDER BY SYSUPD_YMD DESC, SYSUPD_HMS DESC

--Find first 50 data
SELECT * FROM SNTD0050 WHERE ROWNUM <= 50 ORDER BY SYSUPD_YMD DESC, SYSUPD_HMS DESC


